version: "3"

services:
  fever-bot:
    container_name: fever-bot
    build: ./
    ports:
      - 3001:8080
    command: dev
    volumes:
      - ./src:/src
    restart: always
    env_file:
      - .env
